dragon-drop settings

diff --git a/root/system-setup b/root/system-setup
--- a/root/system-setup
+++ b/root/system-setup
@@ -132,6 +132,30 @@ pass_git_setup() {
     fi
 }
 
+dragon_setup() {
+    build_dir=/tmp/build
+    mkdir -p $build_dir
+    latest_tag=$(curl -s https://api.github.com/repos/mwh/dragon/releases/latest | grep "tag_name" | cut -d '"' -f 4)
+    tarball_url=$(curl -s https://api.github.com/repos/mwh/dragon/releases/latest | grep "tarball_url" | cut -d '"' -f 4)
+    file_name="dragon-${latest_tag}.tar.gz"
+    for dir in $build_dir/*dragon-*/; do
+        if [ -d "$dir" ]; then
+            rm -rf $dir
+        fi
+    done
+    if curl -L "$tarball_url" -o "$build_dir/$file_name"; then
+        cd $build_dir
+        tar -xzf "${file_name}" || echo "Error while extracting ${file_name}" >&2
+        extracted_dir=$(tar -tf "$file_name" | grep -o '^[^/]\+' | uniq)
+        echo "extracted to $extracted_dir"
+        cd $extracted_dir
+        make PREFIX=/usr NAME=dragon-drop install
+    else
+        echo "Failed to download pass-git-helper release"
+        exit 1
+    fi
+}
+
 initramfs_setup() {
     akmods --force
     dracut --force
